### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by mXtbZ** [nsonaniya2010/SubDomainizer#18]
Option to have a timeout, some websites keep parsing for 30 min.. Timeout option would be a solution to skip such sites

**Comment by nsonaniya2010** [comment]
I will check this out. Although I will re-write the whole tool again and will keep in mind to add timeout.

**Comment by mXtbZ** [comment]
Hi, thanks for your quick reply, any idea when ? Thanks for the great work !

**Comment by nsonaniya2010** [comment]
Thankyou :)  Probably by this month.

**Comment by nsonaniya2010** [comment]
Hi,
The problem lies while making request to a URL (specifically github). I've added a timeout of 60 Second and if connection failed to establish in that timeline then it will skip that request. 
Although I am keeping this issue open as I will re-write the tool so to think to add that option.

Thanks.

**Comment by nsonaniya2010** [comment]
I think this has already been fixed.
